apiVersion: v1
kind: ConfigMap
metadata:
  name: products-service-config
  namespace: asset-spy
data:
  SERVER_PORT: "8081"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/asset_spy_db"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_DEFAULT_SCHEMA: "asset_spy_products_service_db"

  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-broker:9092"
  KAFKA_VENDOR_TOPIC_PREFIX: "topic_vendor_"
  KAFKA_LISTENER_PREFIX: "kafkaListenerId-"
  KAFKA_CONCURRENCY: "3"
  KAFKA_CONSUMER_PROPERTIES_BOOTSTRAP_SERVERS: "kafka-broker:9092"
  KAFKA_CONSUMER_PROPERTIES_GROUP_ID: "asset-spy-products-service"
  KAFKA_CONSUMER_PROPERTIES_AUTO_OFFSET_RESET: "earliest"
