apiVersion: v1
kind: Service
metadata:
  name: products-service
  namespace: asset-spy
spec:
  selector:
    app: products-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP